'use strict';function n(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}}function r(a){var b=typeof Symbol!="undefined"&&Symbol.iterator&&a[Symbol.iterator];if(b)return b.call(a);if(typeof a.length=="number")return{next:n(a)};throw Error(String(a)+" is not an iterable or ArrayLike");}var u=typeof Object.defineProperties=="function"?Object.defineProperty:function(a,b,e){if(a==Array.prototype||a==Object.prototype)return a;a[b]=e.value;return a};
function y(a){a=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var b=0;b<a.length;++b){var e=a[b];if(e&&e.Math==Math)return e}throw Error("Cannot find global object");}var z=y(this);function A(a,b){if(b)a:{var e=z;a=a.split(".");for(var f=0;f<a.length-1;f++){var k=a[f];if(!(k in e))break a;e=e[k]}a=a[a.length-1];f=e[a];b=b(f);b!=f&&b!=null&&u(e,a,{configurable:!0,writable:!0,value:b})}}
function B(a){if(!(a instanceof Object))throw new TypeError("Iterator result "+a+" is not an object");}function C(){this.A=!1;this.m=null;this.j=void 0;this.i=1;this.o=this.v=0;this.H=this.l=null}function D(a){if(a.A)throw new TypeError("Generator is already running");a.A=!0}C.prototype.F=function(a){this.j=a};function E(a,b){a.l={N:b,isException:!0};a.i=a.v||a.o}C.prototype.getNextAddressJsc=function(){return this.i};C.prototype.getYieldResultJsc=function(){return this.j};
C.prototype.return=function(a){this.l={return:a};this.i=this.o};C.prototype["return"]=C.prototype.return;C.prototype.R=function(a){this.l={B:a};this.o<a?(this.i=a,this.l=null):this.i=this.o};C.prototype.jumpThroughFinallyBlocks=C.prototype.R;C.prototype.h=function(a,b){this.i=b;return{value:a}};C.prototype.yield=C.prototype.h;C.prototype.S=function(a,b){a=r(a);var e=a.next();B(e);if(e.done)this.j=e.value,this.i=b;else return this.m=a,this.h(e.value,b)};C.prototype.yieldAll=C.prototype.S;
C.prototype.B=function(a){this.i=a};C.prototype.jumpTo=C.prototype.B;C.prototype.u=function(){this.i=0};C.prototype.jumpToEnd=C.prototype.u;C.prototype.D=function(a,b){this.v=a;b!=void 0&&(this.o=b)};C.prototype.setCatchFinallyBlocks=C.prototype.D;C.prototype.L=function(a){this.v=0;this.o=a||0};C.prototype.setFinallyBlock=C.prototype.L;C.prototype.K=function(a,b){this.i=a;this.v=b||0};C.prototype.leaveTryBlock=C.prototype.K;C.prototype.C=function(a){this.v=a||0;a=this.l.N;this.l=null;return a};
C.prototype.enterCatchBlock=C.prototype.C;C.prototype.G=function(a,b,e){e?this.H[e]=this.l:this.H=[this.l];this.v=a||0;this.o=b||0;this.l=null};C.prototype.enterFinallyBlock=C.prototype.G;C.prototype.I=function(a,b){b=this.H.splice(b||0)[0];(b=this.l=this.l||b)?b.isException?this.i=this.v||this.o:b.B!=void 0&&this.o<b.B?(this.i=b.B,this.l=null):this.i=this.o:this.i=a};C.prototype.leaveFinallyBlock=C.prototype.I;C.prototype.P=function(a){return new F(a)};C.prototype.forIn=C.prototype.P;
function F(a){this.j=a;this.h=[];for(var b in a)this.h.push(b);this.h.reverse()}F.prototype.i=function(){for(;this.h.length>0;){var a=this.h.pop();if(a in this.j)return a}return null};F.prototype.getNext=F.prototype.i;function G(a){this.h=new C;this.i=a}function H(a,b){D(a.h);var e=a.h.m;if(e)return I(a,"return"in e?e["return"]:function(f){return{value:f,done:!0}},b,a.h.return);a.h.return(b);return J(a)}
function I(a,b,e,f){try{var k=b.call(a.h.m,e);B(k);if(!k.done)return a.h.A=!1,k;var l=k.value}catch(g){return a.h.m=null,E(a.h,g),J(a)}a.h.m=null;f.call(a.h,l);return J(a)}function J(a){for(;a.h.i;)try{var b=a.i(a.h);if(b)return a.h.A=!1,{value:b.value,done:!1}}catch(e){a.h.j=void 0,E(a.h,e)}a.h.A=!1;if(a.h.l){b=a.h.l;a.h.l=null;if(b.isException)throw b.N;return{value:b.return,done:!0}}return{value:void 0,done:!0}}
function K(a){this.next=function(b){D(a.h);a.h.m?b=I(a,a.h.m.next,b,a.h.F):(a.h.F(b),b=J(a));return b};this.throw=function(b){D(a.h);if(a.h.m){var e=a.h.m["throw"];if(e)var f=I(a,e,b,a.h.F);else{b=a.h.m;a.h.m=null;try{b["return"]&&(f=b["return"](),B(f)),E(a.h,new TypeError("The iterator does not provide a 'throw' method."))}catch(k){E(a.h,k)}f=J(a)}}else E(a.h,b),f=J(a);return f};this.return=function(b){return H(a,b)};this[Symbol.iterator]=function(){return this}}
function L(a){function b(f){return a.next(f)}function e(f){return a.throw(f)}return new Promise(function(f,k){function l(g){g.done?f(g.value):Promise.resolve(g.value).then(b,e).then(l,k)}l(a.next())})}function M(a){return L(new K(new G(a)))}
A("Symbol",function(a){function b(l){if(this instanceof b)throw new TypeError("Symbol is not a constructor");return new e(f+(l||"")+"_"+k++,l)}function e(l,g){this.h=l;u(this,"description",{configurable:!0,writable:!0,value:g})}if(a)return a;e.prototype.toString=function(){return this.h};var f="jscomp_symbol_"+(Math.random()*1E9>>>0)+"_",k=0;return b});
A("Symbol.iterator",function(a){if(a)return a;a=Symbol("Symbol.iterator");u(Array.prototype,a,{configurable:!0,writable:!0,value:function(){return N(n(this))}});return a});function N(a){a={next:a};a[Symbol.iterator]=function(){return this};return a}
A("Promise",function(a){function b(g){this.i=0;this.j=void 0;this.h=[];this.u=!1;var c=this.l();try{g(c.resolve,c.reject)}catch(d){c.reject(d)}}function e(){this.h=null}function f(g){return g instanceof b?g:new b(function(c){c(g)})}if(a)return a;e.prototype.i=function(g){if(this.h==null){this.h=[];var c=this;this.j(function(){c.m()})}this.h.push(g)};var k=z.setTimeout;e.prototype.j=function(g){k(g,0)};e.prototype.m=function(){for(;this.h&&this.h.length;){var g=this.h;this.h=[];for(var c=0;c<g.length;++c){var d=
g[c];g[c]=null;try{d()}catch(h){this.l(h)}}}this.h=null};e.prototype.l=function(g){this.j(function(){throw g;})};b.prototype.l=function(){function g(h){return function(m){d||(d=!0,h.call(c,m))}}var c=this,d=!1;return{resolve:g(this.F),reject:g(this.m)}};b.prototype.F=function(g){if(g===this)this.m(new TypeError("A Promise cannot resolve to itself"));else if(g instanceof b)this.H(g);else{a:switch(typeof g){case "object":var c=g!=null;break a;case "function":c=!0;break a;default:c=!1}c?this.D(g):this.o(g)}};
b.prototype.D=function(g){var c=void 0;try{c=g.then}catch(d){this.m(d);return}typeof c=="function"?this.I(c,g):this.o(g)};b.prototype.m=function(g){this.v(2,g)};b.prototype.o=function(g){this.v(1,g)};b.prototype.v=function(g,c){if(this.i!=0)throw Error("Cannot settle("+g+", "+c+"): Promise already settled in state"+this.i);this.i=g;this.j=c;this.i===2&&this.G();this.A()};b.prototype.G=function(){var g=this;k(function(){if(g.C()){var c=z.console;typeof c!=="undefined"&&c.error(g.j)}},1)};b.prototype.C=
function(){if(this.u)return!1;var g=z.CustomEvent,c=z.Event,d=z.dispatchEvent;if(typeof d==="undefined")return!0;typeof g==="function"?g=new g("unhandledrejection",{cancelable:!0}):typeof c==="function"?g=new c("unhandledrejection",{cancelable:!0}):(g=z.document.createEvent("CustomEvent"),g.initCustomEvent("unhandledrejection",!1,!0,g));g.promise=this;g.reason=this.j;return d(g)};b.prototype.A=function(){if(this.h!=null){for(var g=0;g<this.h.length;++g)l.i(this.h[g]);this.h=null}};var l=new e;b.prototype.H=
function(g){var c=this.l();g.J(c.resolve,c.reject)};b.prototype.I=function(g,c){var d=this.l();try{g.call(c,d.resolve,d.reject)}catch(h){d.reject(h)}};b.prototype.then=function(g,c){function d(q,t){return typeof q=="function"?function(w){try{h(q(w))}catch(x){m(x)}}:t}var h,m,p=new b(function(q,t){h=q;m=t});this.J(d(g,h),d(c,m));return p};b.prototype.catch=function(g){return this.then(void 0,g)};b.prototype.J=function(g,c){function d(){switch(h.i){case 1:g(h.j);break;case 2:c(h.j);break;default:throw Error("Unexpected state: "+
h.i);}}var h=this;this.h==null?l.i(d):this.h.push(d);this.u=!0};b.resolve=f;b.reject=function(g){return new b(function(c,d){d(g)})};b.race=function(g){return new b(function(c,d){for(var h=r(g),m=h.next();!m.done;m=h.next())f(m.value).J(c,d)})};b.all=function(g){var c=r(g),d=c.next();return d.done?f([]):new b(function(h,m){function p(w){return function(x){q[w]=x;t--;t==0&&h(q)}}var q=[],t=0;do q.push(void 0),t++,f(d.value).J(p(q.length-1),m),d=c.next();while(!d.done)})};return b});
function O(a,b){return Object.prototype.hasOwnProperty.call(a,b)}
A("WeakMap",function(a){function b(d){this.h=(c+=Math.random()+1).toString();if(d){d=r(d);for(var h;!(h=d.next()).done;)h=h.value,this.set(h[0],h[1])}}function e(){}function f(d){var h=typeof d;return h==="object"&&d!==null||h==="function"}function k(d){if(!O(d,g)){var h=new e;u(d,g,{value:h})}}function l(d){var h=Object[d];h&&(Object[d]=function(m){if(m instanceof e)return m;Object.isExtensible(m)&&k(m);return h(m)})}if(function(){if(!a||!Object.seal)return!1;try{var d=Object.seal({}),h=Object.seal({}),
m=new a([[d,2],[h,3]]);if(m.get(d)!=2||m.get(h)!=3)return!1;m.delete(d);m.set(h,4);return!m.has(d)&&m.get(h)==4}catch(p){return!1}}())return a;var g="$jscomp_hidden_"+Math.random();l("freeze");l("preventExtensions");l("seal");var c=0;b.prototype.set=function(d,h){if(!f(d))throw Error("Invalid WeakMap key");k(d);if(!O(d,g))throw Error("WeakMap key fail: "+d);d[g][this.h]=h;return this};b.prototype.get=function(d){return f(d)&&O(d,g)?d[g][this.h]:void 0};b.prototype.has=function(d){return f(d)&&O(d,
g)&&O(d[g],this.h)};b.prototype.delete=function(d){return f(d)&&O(d,g)&&O(d[g],this.h)?delete d[g][this.h]:!1};return b});
A("Map",function(a){function b(){var c={};return c.previous=c.next=c.head=c}function e(c,d){var h=c[1];return N(function(){if(h){for(;h.head!=c[1];)h=h.previous;for(;h.next!=h.head;)return h=h.next,{done:!1,value:d(h)};h=null}return{done:!0,value:void 0}})}function f(c,d){var h=d&&typeof d;h=="object"||h=="function"?l.has(d)?h=l.get(d):(h=""+ ++g,l.set(d,h)):h="p_"+d;var m=c[0][h];if(m&&O(c[0],h))for(c=0;c<m.length;c++){var p=m[c];if(d!==d&&p.key!==p.key||d===p.key)return{id:h,list:m,index:c,entry:p}}return{id:h,
list:m,index:-1,entry:void 0}}function k(c){this[0]={};this[1]=b();this.size=0;if(c){c=r(c);for(var d;!(d=c.next()).done;)d=d.value,this.set(d[0],d[1])}}if(function(){if(!a||typeof a!="function"||!a.prototype.entries||typeof Object.seal!="function")return!1;try{var c=Object.seal({x:4}),d=new a(r([[c,"s"]]));if(d.get(c)!="s"||d.size!=1||d.get({x:4})||d.set({x:4},"t")!=d||d.size!=2)return!1;var h=d.entries(),m=h.next();if(m.done||m.value[0]!=c||m.value[1]!="s")return!1;m=h.next();return m.done||m.value[0].x!=
4||m.value[1]!="t"||!h.next().done?!1:!0}catch(p){return!1}}())return a;var l=new WeakMap;k.prototype.set=function(c,d){c=c===0?0:c;var h=f(this,c);h.list||(h.list=this[0][h.id]=[]);h.entry?h.entry.value=d:(h.entry={next:this[1],previous:this[1].previous,head:this[1],key:c,value:d},h.list.push(h.entry),this[1].previous.next=h.entry,this[1].previous=h.entry,this.size++);return this};k.prototype.delete=function(c){c=f(this,c);return c.entry&&c.list?(c.list.splice(c.index,1),c.list.length||delete this[0][c.id],
c.entry.previous.next=c.entry.next,c.entry.next.previous=c.entry.previous,c.entry.head=null,this.size--,!0):!1};k.prototype.clear=function(){this[0]={};this[1]=this[1].previous=b();this.size=0};k.prototype.has=function(c){return!!f(this,c).entry};k.prototype.get=function(c){return(c=f(this,c).entry)&&c.value};k.prototype.entries=function(){return e(this,function(c){return[c.key,c.value]})};k.prototype.keys=function(){return e(this,function(c){return c.key})};k.prototype.values=function(){return e(this,
function(c){return c.value})};k.prototype.forEach=function(c,d){for(var h=this.entries(),m;!(m=h.next()).done;)m=m.value,c.call(d,m[1],m[0],this)};k.prototype[Symbol.iterator]=k.prototype.entries;var g=0;return k});A("Object.entries",function(a){return a?a:function(b){var e=[],f;for(f in b)O(b,f)&&e.push([f,b[f]]);return e}});function aa(a){this.h=a}var P;function ba(){var a=P;a.h.runtime.getPlatformInfo();setInterval(function(){a.h.runtime.getPlatformInfo()},2E4)};function Q(a,b,e){if(typeof a==="object"&&typeof b==="string"){var f=a;a=b}else if(typeof a==="string"&&typeof b==="function")e=b;else return{lang:"",M:!1};return{lang:a,T:e,O:f,M:!0}}function ca(a){M(function(b){return b.return(da(a))})}function ea(a){M(function(b){if(b.i==1)return b.h(R(S),2);if(!b.j)return b.return();S.m&&S.m(a);a.type!=="end"&&a.type!=="error"||T(S);b.u()})}function U(a){return M(function(b){return b.i==1?b.h(a.h.offscreen.hasDocument(),2):b.return(b.j)})}
function V(a){var b,e;return M(function(f){switch(f.i){case 1:return f.h(U(a),2);case 2:if(f.j)return f.return();f.D(3);return f.h(a.h.offscreen.createDocument({url:"offscreen.html",reasons:[a.h.offscreen.Reason.AUDIO_PLAYBACK,a.h.offscreen.Reason.USER_MEDIA],justification:"Required for Text-to-Speech audio synthesis and playback"}),5);case 5:return b={type:"init"},f.h(a.h.runtime.sendMessage(b),6);case 6:T(a);f.K(4);break;case 3:e=f.C(),console.error("Failed to create offscreen document:",e);case 4:return f.h(fa(a.i),
0)}})}function ha(a){M(function(b){if(b.i==1)return b.h(U(a),2);if(b.i!=3)return b.j?b.h(a.h.offscreen.closeDocument(),3):b.return();b.u()})}function R(a){var b;return M(function(e){if(e.i==1)return e.D(2),e.h(V(a),4);if(e.i!=2)return e.return(!0);b=e.C();console.error("Error ensuring offscreen document is ready:",b);return e.return(!1)})}function W(a){a.l&&(clearTimeout(a.l),a.l=void 0)}function T(a){W(a);a.l=setTimeout(function(){ha(a)},3E5)};function ia(){this.h=chrome;this.i=new Map}function ja(a,b){var e,f,k;return M(function(l){if(l.i==1)return e={type:"getLanguageStatus",lang:b},l.h(a.h.runtime.sendMessage(e),2);f=l.j;k={lang:f.lang,installStatus:f.status};a.h.ttsEngine.updateLanguage(k);l.u()})}
function ka(a){var b=S.i,e,f,k,l,g,c,d,h,m,p,q,t,w,x;M(function(v){e=[];f=r(Object.entries(a));k=f.next();try{for(;!k.done;k=f.next()){g=k.value;c=r(g);d=c.next().value;h=c.next().value;m=d;p=h;q=r(p);t=q.next();try{for(;!t.done;t=q.next())x=t.value,e.push({lang:m,voiceName:x,eventTypes:["start","end","error","word"]})}finally{t&&!t.done&&(w=q.return)&&w.call(q)}}}finally{k&&!k.done&&(l=f.return)&&l.call(f)}b.h.ttsEngine.updateVoices(e);v.u()})}
function da(a){var b=S.i,e,f;return M(function(k){if(k.i==1)return b.i.get(a)==="uninstallLanguage"&&b.i.delete(a),k.h(X(b),2);e=k.j;e[a]=Date.now();f={};return k.h(b.h.storage.local.set((f.lastUsedTimestamps=e,f)),0)})}
function fa(a){var b,e,f,k,l,g,c,d,h,m;return M(function(p){switch(p.i){case 1:return p.h(Y(a),2);case 2:return(b=p.j)?p.h(X(a),3):p.return();case 3:e=p.j;f=la(b,e);if(f.length===0)return p.return();k=r(f);l=k.next();p.L(4);case 6:if(l.done){p.B(4);break}c=l.value;d={type:"removeUnusedLanguage",lang:c};return p.h(a.h.runtime.sendMessage(d),9);case 9:c in b&&delete b[c];c in e&&delete e[c];l=k.next();p.B(6);break;case 4:p.G();l&&!l.done&&(g=k.return)&&g.call(k);p.I(5);break;case 5:return h={},p.h(a.h.storage.local.set((h.installedTimestamps=
b,h)),10);case 10:return m={},p.h(a.h.storage.local.set((m.lastUsedTimestamps=e,m)),0)}})}function la(a,b){var e=Date.now();return Object.entries(a).filter(function(f){var k=r(f);f=k.next().value;k=k.next().value;var l=f in b;return e-Number(l?b[f]:k)>(l?7776E6:12096E5)}).map(function(f){return r(f).next().value})}function Z(a){a.j&&clearTimeout(a.j);a.j=setTimeout(function(){ma(a)},200)}
function ma(a){var b,e,f,k,l,g,c,d,h,m,p,q,t,w,x;M(function(v){switch(v.i){case 1:if(a.i.size===0)return v.return();b=new Map(a.i);a.i.clear();e=[];f=[];k=r(b);l=k.next();v.L(2);case 4:if(l.done){v.B(2);break}c=l.value;d=r(c);h=d.next().value;m=d.next().value;p=h;q=m;t={type:q,lang:p};return v.h(a.h.runtime.sendMessage(t),7);case 7:w=v.j;x={lang:w.lang,installStatus:w.status};a.h.ttsEngine.updateLanguage(x);switch(w.status){case a.h.ttsEngine.LanguageInstallStatus.INSTALLED:e.push(p);break;case a.h.ttsEngine.LanguageInstallStatus.NOT_INSTALLED:f.push(p)}l=
k.next();v.B(4);break;case 2:v.G();l&&!l.done&&(g=k.return)&&g.call(k);v.I(3);break;case 3:return v.h(na(a,f),8);case 8:return v.return(oa(a,e))}})}function na(a,b){var e,f,k,l,g,c;return M(function(d){if(d.i==1)return d.h(Y(a),2);e=d.j;f=r(b);k=f.next();try{for(;!k.done;k=f.next())g=k.value,delete e[g]}finally{k&&!k.done&&(l=f.return)&&l.call(f)}c={};return d.h(a.h.storage.local.set((c.installedTimestamps=e,c)),0)})}
function oa(a,b){var e,f,k;return M(function(l){if(l.i==1)return e=Date.now(),l.h(Y(a),2);f=l.j;b.forEach(function(g){f[g]=e});k={};return l.h(a.h.storage.local.set((k.installedTimestamps=f,k)),0)})}function Y(a){var b;return M(function(e){if(e.i==1)return e.h(a.h.storage.local.get("installedTimestamps"),2);b=e.j;return e.return(b.installedTimestamps||{})})}
function X(a){var b;return M(function(e){if(e.i==1)return e.h(a.h.storage.local.get("lastUsedTimestamps"),2);b=e.j;return e.return(b.lastUsedTimestamps||{})})};var S=new function(){var a=new ia,b=this;this.h=chrome;this.i=a;this.C=function(e,f,k){var l,g,c;return M(function(d){switch(d.i){case 1:return W(b),d.h(R(b),2);case 2:if(!d.j)return k({type:"error",errorMessage:"Offscreen document not ready."}),d.return();b.m=k;l={type:"speak",utterance:e,options:f};d.D(3);return d.h(b.h.runtime.sendMessage(l),5);case 5:d.K(0);break;case 3:g=d.C(),c=g instanceof Error?g.message:"Error while trying to speak.",k({type:"error",errorMessage:c}),d.u()}})};this.D=function(){var e;
return M(function(f){if(f.i==1)return f.h(R(b),2);if(f.i!=3){if(!f.j)return T(b),f.return();b.m=void 0;e={type:"stop"};return f.h(b.h.runtime.sendMessage(e),3)}T(b);f.u()})};this.v=function(){var e;return M(function(f){if(f.i==1)return f.h(R(b),2);if(!f.j)return f.return();e={type:"pause"};return f.h(b.h.runtime.sendMessage(e),0)})};this.A=function(){var e;return M(function(f){if(f.i==1)return f.h(R(b),2);if(!f.j)return f.return();e={type:"resume"};return f.h(b.h.runtime.sendMessage(e),0)})};this.o=
function(e,f,k){var l,g,c,d,h,m,p;return M(function(q){if(q.i==1)return q.h(R(b),2);if(!q.j)return q.return();l=Q(e,f,k);g=l.lang;c=l.O;d=l.M;p=(m=(h=c)==null?void 0:h.source)!=null?m:"unknown";if(!d||p!==b.j)return q.return();var t=b.i;t.i.set(g,"installLanguage");Z(t);t.h.ttsEngine.updateLanguage({lang:g,installStatus:t.h.ttsEngine.LanguageInstallStatus.INSTALLING});q.u()})};this.u=function(e,f,k){var l,g,c,d,h,m,p;return M(function(q){if(q.i==1)return q.h(R(b),2);if(!q.j)return q.return();l=Q(e,
f,k);g=l.lang;c=l.O;d=l.M;p=(m=(h=c)==null?void 0:h.source)!=null?m:"unknown";return d&&p===b.j?q.return(ja(b.i,g)):q.return()})};this.F=function(e,f){return M(function(k){if(k.i==1)return k.h(R(b),2);if(!k.j||e.source!==b.j)return k.return();var l=b.i;l.i.set(f,"uninstallLanguage");Z(l);k.u()})};this.j=this.h.ttsEngine.TtsClientSource.CHROMEFEATURE;this.h.runtime.onInstalled.addListener(function(){return M(function(e){return e.h(V(b),0)})});this.h.runtime.onStartup.addListener(function(){return M(function(e){return e.h(R(b),
0)})});this.h.ttsEngine.onSpeak.addListener(this.C);this.h.ttsEngine.onStop.addListener(this.D);this.h.ttsEngine.onPause.addListener(this.v);this.h.ttsEngine.onResume.addListener(this.A);this.h.ttsEngine.onInstallLanguageRequest.addListener(this.o);this.h.ttsEngine.onLanguageStatusRequest.addListener(this.u);this.h.ttsEngine.onUninstallLanguageRequest.addListener(this.F);P||(P=new aa(this.h),ba())};
chrome.runtime.onMessage.addListener(function(a){a.type==="offscreenVoicesResponse"?ka(a.voices):a.type==="offscreenTtsEventResponse"?ea(a.event):a.type==="languageUsed"&&ca(a.language)});
